### ISSUE TITLE
Preserving comment-only lines?

### ISSUE THREAD

**Issue by di** [tox-dev/pyproject-fmt#16]
Currently this project only preserves comments when they're on a line with syntax, otherwise they are removed:

`pyproject.toml`:
```toml
[project]
# A comment-only line
name = "something"  # This is the name
# Another comment
```

```
$ python -m pyproject_fmt pyproject.toml
--- pyproject.toml

+++ pyproject.toml

@@ -1,4 +1,2 @@

 [project]
-# A comment-only line
 name = "something"  # This is the name
-# Another comment
```

Seems like it would make sense to either:
- a) preserve all comments
- b) remove all comments

My personal opinion is that a) would be ideal!

**Comment by gaborbernat** [comment]
Yeah, a is the expected behaviour.

**Comment by tusharsadhwani** [comment]
I'll try and fix this.

**Comment by tusharsadhwani** [comment]
https://github.com/tox-dev/pyproject-fmt/blob/6b7536f11ccffdc5a316099730ab09eb932fd1c5/src/pyproject_fmt/formatter/util.py#L41

This seems to be the bug. `entries` gets rid of all non key-value lines from `body`.

**Comment by tusharsadhwani** [comment]
Possible convention:
- If a comment has a key-value line below it and nothing/whitespace above it, it belongs to that line.
- If a comment has a key-value line above it and nothing/whitespace below it, it belongs to that line.
- If a comment has a key-value line both above it AND below it, we assume it belongs to the line below.

**Comment by gaborbernat** [comment]
I think all comments up to a key belong to that key. However, comments that don't have any key after them (comments at the end of file) should be kept.

**Comment by tusharsadhwani** [comment]
@gaborbernat what about this:

```toml
[options.entry_points]
# some comment about the project in general

b = 20
a = 10
```

when you sort the entry points, you don't want the top level comment to be dragged with `b = 20`

**Comment by gaborbernat** [comment]
I don't agree, I think it should be dragged 🤔

**Comment by tusharsadhwani** [comment]
is this the desired outcome?

```toml
[options.entry_points]
a = 10
# some comment about the project in general

b = 20
```

**Comment by gaborbernat** [comment]
More like:

```toml
[options.entry_points]
a = 10  # some comment about the project in general
b = 20
```

If fits in one line, otherwise:


```toml
[options.entry_points]
 # some comment about the project in general
a = 10
b = 20
```

I can see an argument for putting comments after the key it belongs to too. Need to have a think. One of those two. Generally, whitespace should be collapsed IMHO.

**Comment by tusharsadhwani** [comment]
I see, that makes sense. Something got misunderstood before.

When you say "all comments up to a key belong to that key", in this case:

```toml
[foo]
# bar

x = 10
y = 20
```

that would mean `# bar` belongs to `x = 10`. Which doesn't seem right to me, `# bar` here it is more like its own little block, unrelated to any key.

Which I believe is what you're thinking of as well.

**Comment by tusharsadhwani** [comment]
@gaborbernat honestly i don't think I'd be able to get back to this. i have an unfinished PR as a starting point if someone wants to take it up.

**Comment by adamtheturtle** [comment]
I hit the exact same issue as `amotl`. I'm happy to make a new issue if preferred.

What I want:

```toml
[project.optional-dependencies]
dev = [
    "check-manifest",
    # Comment about why we pin doc8 to this version
    "doc8==0.11.2",
]
```

The comment is associated with `doc8`.
`pyproject-fmt` moves the comment next to `"check-manifest"`.
