### ISSUE TITLE
"pre-commit autoupdate" updates to 1e2ad21bf1bfe403be122f3a8fc984cad8f5b085

### ISSUE THREAD

**Issue by TheLovinator1** [tox-dev/pyproject-fmt#188]
When I run `pre-commit autoupdate` it updates to `1e2ad21bf1bfe403be122f3a8fc984cad8f5b085`.

`https://github.com/tox-dev/pyproject-fmt updating 1.7.0 -> 1e2ad21bf1bfe403be122f3a8fc984cad8f5b085`

Some problems:
1. This update needs the Rust toolchain to be installed:
```
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\lovinator\\.cache\\pre-commit\\repoicmye84g\\py_env-python3\\Scripts\\python.EXE', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing c:\users\lovinator\.cache\pre-commit\repoicmye84g
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'error'
stderr:
      error: subprocess-exited-with-error

      Preparing metadata (pyproject.toml) did not run successfully.
      exit code: 1

      [6 lines of output]

      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/
```

2. After installing Rust it will always fail because it tries to move the following between two places:

```toml
[tool.poetry.group.dev.dependencies]
ruff = "^0.4.0"
pre-commit = "^3.7.0"
```

3. Not a problem but I think the new style looks worse:

```toml
[tool.poetry.dependencies]
python = "^3.12"
Django = "^5.0.6"
python-dotenv = "^1.0.1"
psycopg = { extras = [
  "binary",
], version = "^3.1.18" }
django-redis = { extras = [
  "hiredis",
], version = "^5.4.0" }
gunicorn = "^22.0.0"
loguru = "^0.7.2"
```

vs old version

```toml
[tool.poetry.dependencies]
python = "^3.12"
Django = "^5.0.6"
python-dotenv = "^1.0.1"
psycopg = { extras = ["binary"], version = "^3.1.18" }
django-redis = { extras = ["hiredis"], version = "^5.4.0" }
gunicorn = "^22.0.0"
loguru = "^0.7.2"
```
