### ISSUE TITLE
Removes 3.13, CPython and PyPy classifiers

### ISSUE THREAD

**Issue by hugovk** [tox-dev/pyproject-fmt#198]
Exciting to see the new release! 🎉 

I have this in pre-commit:

```yaml
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: 2.0.2
    hooks:
      - id: pyproject-fmt
        additional_dependencies: [tox]
```

And `py313` in tox.ini:

```ini
[tox]
requires =
    tox>=4.2
env_list =
    cog
    cli
    lint
    pins
    py{py3, 313, 312, 311, 310, 39, 38}
```

But pyproject-fmt 2.0.2 is removing the 3.13 Trove classifier:

```diff
   "Programming Language :: Python :: 3.10",
   "Programming Language :: Python :: 3.11",
   "Programming Language :: Python :: 3.12",
-  "Programming Language :: Python :: 3.13",
-  "Programming Language :: Python :: Implementation :: CPython",
-  "Programming Language :: Python :: Implementation :: PyPy",
```

https://pyproject-fmt.readthedocs.io/en/latest/#calculating-max-supported-python-version says it should read the tox config for the upper bound.

For example: https://github.com/hugovk/norwegianblue/pull/212

I'd also like to keep the "Implementation" classifiers to make it clear PyPy is supported.

---

Edit: PR https://github.com/tox-dev/pyproject-fmt-rust/pull/4 will preserve the Implementation classifiers.
