### ISSUE TITLE
Ordering of [build-system]

### ISSUE THREAD

**Issue by henryiii** [tox-dev/pyproject-fmt#22]
Currently, the PEPs, documentation, and projects use the following order for build-system:

```toml
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
# backend-path here
```

However, `pyproject-fmt` [enforces a different order](https://github.com/tox-dev/pyproject-fmt/blob/main/src/pyproject_fmt/formatter/build_system.py#L18):

```python
order_keys(system, ("build-backend", "requires", "backend-path"))
```

```toml
[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools"]
# backend-path here
```

This highlights build-backend, but is reverse the underlying order (first the environment is setup, then the build-backend is called), and is counter to most of the existing examples and documentation. I personally would really like the PEP order to be enforced, rather than having to change scikit-hep/developer, packaging.python.org, scikit-hep/cookie, etc. But I'm happy to follow a standard even if it's not my preference.

I admit, if it had always been done this way, I'd probably have been fine with with the reversed order. Though I do logically prefer environment then build hook, since it maps to what is happening underneath better.

At the very least, build-backend and backend-path should not flip-flop positions if you change from one to the other. Simple alphabetical would put them in together, at least. ;)

Thoughts? Votes? Suggestions?
