### ISSUE TITLE
build requirement gets removed for no apparent reason

### ISSUE THREAD

**Issue by Dobatymo** [tox-dev/pyproject-fmt#269]
### Discussed in https://github.com/tox-dev/pyproject-fmt/discussions/265

Hi, great project!

I have the following in my pyproject file

```toml
[build-system]
requires = [
  "cython==3.0.11",
  "numpy==1.22.2; python_version<'3.9'",
  "numpy>=2; python_version>='3.9'",
  "setuptools",
]
```
when running `pyproject-fmt==2.2.4` using pre-commit the ` "numpy==1.22.2; python_version<'3.9'",` line gets removed. It looks like a bug.
