### ISSUE TITLE
Every run of pre-commit adds a newline after [tool.mypy]

### ISSUE THREAD

**Issue by MindTooth** [tox-dev/pyproject-fmt#69]
Hi.

I think that https://github.com/tox-dev/pyproject-fmt/pull/67 added a bug where it keep adds a newline.

After several runs, I get the following:
```toml
[[tool.mypy.overrides]]
module = "vendor.*"
ignore_errors = true

















[tool.ruff]
exclude = [
  ".git",
````

Message after a run:
```
$ pyproject-fmt pyproject.toml
--- pyproject.toml

+++ pyproject.toml

@@ -174,6 +174,7 @@

 
 
 
+
 [tool.ruff]
 exclude = [
   ".git",
```

I'll gladly provide more if you need it.
