### ISSUE TITLE
Incorrectly changes build-system requires to double quotes

### ISSUE THREAD

**Issue by wwuck** [tox-dev/pyproject-fmt#94]
I am using single quotes throughout my `pyproject.toml` files.

Example:
```toml
[build-system]
build-backend = 'poetry_dynamic_versioning.backend'
requires = [
  'poetry-core>=1',
  'poetry-dynamic-versioning',
]

[tool.flake8]
min-python-version = '3.11'

[tool.poetry.dependencies]
click = '8.0.3'
python = '~3.11'

[tool.poetry.group.build.dependencies]
check-wheel-contents = '0.4.0'
pre-commit = '2.20.0'
twine = '4.0.2'
```

When I run `pyproject-fmt` on this file, it converts the items in `requires` to double quotes but leaves everything else as single quotes.

```diff
--- pyproject.toml

+++ pyproject.toml

@@ -1,8 +1,8 @@

 [build-system]
 build-backend = 'poetry_dynamic_versioning.backend'
 requires = [
-  'poetry-core>=1',
-  'poetry-dynamic-versioning',
+  "poetry-core>=1",
+  "poetry-dynamic-versioning",
 ]
 
 [tool.flake8]
```

Is there a way to prevent this?
